/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cr.ac.ufide.quiz.cliente.servidor.Vista;
import cr.ac.ufide.quiz.cliente.servidor.Cliente.ClienteJuego;
import cr.ac.ufide.quiz.cliente.servidor.Cliente.EscuchadorCliente;
import java.awt.BorderLayout;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
/**
 *
 * @author jimel
 */
public class FrmConexion extends JFrame implements EscuchadorCliente {


    private ClienteJuego cliente;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmConexion.class.getName());

    /**
     * Creates new form FrmConexion
     */
    public FrmConexion() {
        initComponents();
        setLocationRelativeTo(null);
        configurarEventos();
        lblEstadoConexion.setText("Estado: sin conectar");
        txtIp.setText("127.0.0.1");
        txtPuerto.setText("6500");
    }

    private void configurarEventos() {
        btnConectar.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent e) {
                conectar();
            }
        });

        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent e) {
                System.exit(0);
            }
        });
    }

    private void conectar() {
        String nickname = txtNickname.getText().trim();
        String ip = txtIp.getText().trim();
        String puertoTexto = txtPuerto.getText().trim();

        if (nickname.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debe ingresar un nickname");
            return;
        }

        try {
            int puerto = Integer.parseInt(puertoTexto);

            cliente = new ClienteJuego();
            cliente.setEscuchador(this);
            cliente.conectar(ip, puerto, nickname);

            lblEstadoConexion.setText("Estado: conectando...");
            btnConectar.setEnabled(false);

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "El puerto debe ser numerico");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "No se pudo conectar: " + e.getMessage());
            btnConectar.setEnabled(true);
        }
    }

    @Override
    public void alConectado(String mensaje) {
        lblEstadoConexion.setText("Estado: " + mensaje);

        FrmSala frmSala = new FrmSala(cliente, txtNickname.getText().trim());
        cliente.setEscuchador(frmSala);
        frmSala.setVisible(true);
        dispose();
    }

    @Override
    public void alError(String mensaje) {
        lblEstadoConexion.setText("Estado: " + mensaje);
        btnConectar.setEnabled(true);
    }

    @Override
    public void alMensaje(String mensaje) {
        lblEstadoConexion.setText("Estado: " + mensaje);
    }

    @Override
    public void alJugadores(String datos) {
    }

    @Override
    public void alPregunta(String idPregunta, String enunciado, String opciones) {
    }

    @Override
    public void alResultadoRespuesta(String resultado, int puntos) {
    }

    @Override
    public void alPuntajes(String datos) {
    }

    @Override
    public void alGanador(String nombreGanador, int puntaje) {
    }

    @Override
    public void alDesconectado(String mensaje) {
        lblEstadoConexion.setText("Estado: " + mensaje);
        btnConectar.setEnabled(true);
    }

    public static void main(String[] args) {
        new FrmConexion().setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblIp = new javax.swing.JLabel();
        lblNickname = new javax.swing.JLabel();
        lblPuerto = new javax.swing.JLabel();
        lblEstadoConexion = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txtNickname = new javax.swing.JTextField();
        txtIp = new javax.swing.JTextField();
        txtPuerto = new javax.swing.JTextField();
        btnConectar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        lblSlogan = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(650, 529));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(650, 529));

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(36, 49, 96));
        lblTitulo.setText("Bienvenido a UfideQuiz");

        lblIp.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblIp.setForeground(new java.awt.Color(36, 49, 96));
        lblIp.setText("IP del servidor");

        lblNickname.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblNickname.setForeground(new java.awt.Color(36, 49, 96));
        lblNickname.setText("Nickname");

        lblPuerto.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblPuerto.setForeground(new java.awt.Color(36, 49, 96));
        lblPuerto.setText("Puerto");

        lblEstadoConexion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblEstadoConexion.setForeground(new java.awt.Color(36, 49, 96));
        lblEstadoConexion.setText("Estado");

        jPanel2.setBackground(new java.awt.Color(54, 76, 161));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        txtNickname.addActionListener(this::txtNicknameActionPerformed);

        txtPuerto.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        btnConectar.setText("Conectar");

        btnSalir.setText("Salir");

        lblSlogan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblSlogan.setForeground(new java.awt.Color(54, 76, 161));
        lblSlogan.setText("Demuestra lo que sabes");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(lblEstadoConexion)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblSlogan)
                .addGap(242, 242, 242))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addComponent(lblNickname)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(278, 278, 278)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnConectar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(191, 191, 191)
                            .addComponent(lblTitulo))))
                .addGap(191, 191, 191))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(161, 161, 161)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblPuerto)
                    .addComponent(lblIp)
                    .addComponent(txtNickname, javax.swing.GroupLayout.DEFAULT_SIZE, 335, Short.MAX_VALUE)
                    .addComponent(txtIp)
                    .addComponent(txtPuerto))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSlogan)
                .addGap(28, 28, 28)
                .addComponent(lblNickname)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtNickname, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblIp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtIp, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblPuerto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtPuerto, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(lblEstadoConexion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnConectar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSalir)
                .addGap(46, 46, 46))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 568, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNicknameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNicknameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNicknameActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConectar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblEstadoConexion;
    private javax.swing.JLabel lblIp;
    private javax.swing.JLabel lblNickname;
    private javax.swing.JLabel lblPuerto;
    private javax.swing.JLabel lblSlogan;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextField txtIp;
    private javax.swing.JTextField txtNickname;
    private javax.swing.JTextField txtPuerto;
    // End of variables declaration//GEN-END:variables
}
