/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cr.ac.ufide.quiz.cliente.servidor.Vista;
import cr.ac.ufide.quiz.cliente.servidor.Cliente.ClienteJuego;
import cr.ac.ufide.quiz.cliente.servidor.Cliente.EscuchadorCliente;
import javax.swing.JFrame;

/**
 *
 * @author jimel
 */
// Esta ventana muestra la pregunta actual del juego,
// las opciones disponibles y el puntaje del jugador
public class FrmPregunta extends JFrame implements EscuchadorCliente {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmPregunta.class.getName());

    /**
     * Creates new form FrmPregunta
     */

    private ClienteJuego cliente;
    private String nickname;
    private int[] idsOpciones;
    private String datosPuntajes;

    public FrmPregunta(ClienteJuego cliente, String nickname) {
        this.cliente = cliente;
        this.nickname = nickname;
        this.idsOpciones = new int[4];

        initComponents(); // 🔥 ESTO FALTABA
        setLocationRelativeTo(null);
    }
    // Carga la pregunta recibida y coloca las opciones en los botones
    public void cargarPregunta(String idPregunta, String enunciado, String opciones) {
        lblNumeroPregunta.setText("Pregunta ID: " + idPregunta);
        lblPregunta.setText(enunciado);
        lblEstadoRespuesta.setText("Seleccione una opcion");

        String[] listaOpciones = opciones.split(";");

        for (int i = 0; i < listaOpciones.length && i < 4; i++) {
            String[] partes = listaOpciones[i].split("~");

            if (partes.length >= 2) {
                idsOpciones[i] = Integer.parseInt(partes[0]);

                if (i == 0) btnOpcion1.setText(partes[1]);
                if (i == 1) btnOpcion2.setText(partes[1]);
                if (i == 2) btnOpcion3.setText(partes[1]);
                if (i == 3) btnOpcion4.setText(partes[1]);
            }
        }

        habilitarBotones(true);
    }

    // Envia la respuesta elegida al servidor
    private void responder(int indice) {
        if (indice >= 0 && indice < idsOpciones.length) {
            cliente.enviarRespuesta(idsOpciones[indice]);
            habilitarBotones(false);
            lblEstadoRespuesta.setText("Respuesta enviada");
        }
    }
   // Activa o desactiva los botones de opciones
    private void habilitarBotones(boolean estado) {
        btnOpcion1.setEnabled(estado);
        btnOpcion2.setEnabled(estado);
        btnOpcion3.setEnabled(estado);
        btnOpcion4.setEnabled(estado);
    }





    
    @Override
    public void alConectado(String mensaje) {}

    @Override
    public void alError(String mensaje) {
        lblEstadoRespuesta.setText(mensaje);
    }

    @Override
    public void alMensaje(String mensaje) {
        lblEstadoRespuesta.setText(mensaje);
    }

    @Override
    public void alJugadores(String datos) {}
  // Cuando llega una nueva pregunta, la carga en pantalla
    @Override
    public void alPregunta(String idPregunta, String enunciado, String opciones) {
        cargarPregunta(idPregunta, enunciado, opciones);
    }
    // Muestra si la respuesta fue correcta o incorrecta
    @Override
    public void alResultadoRespuesta(String resultado, int puntos) {
        lblEstadoRespuesta.setText("Resultado: " + resultado + " - puntos: " + puntos);
    }
    // Actualiza el puntaje del jugador actual
    @Override
    public void alPuntajes(String datos) {
        datosPuntajes = datos;

        if (datos == null || datos.isEmpty()) return;

        String[] jugadores = datos.split(";");

        for (String j : jugadores) {
            String[] partes = j.split(":");
            if (partes.length >= 2 && partes[0].equalsIgnoreCase(nickname)) {
                lblPuntajeValor.setText(partes[1]);
            }
        }
    }
    // Abre la ventana final cuando ya hay un ganador
    @Override
    public void alGanador(String nombreGanador, int puntaje) {
        FrmResultados frm = new FrmResultados(cliente);
        frm.cargarResultados(nombreGanador, puntaje, datosPuntajes);
        cliente.setEscuchador(frm);
        frm.setVisible(true);
        dispose();
    }

    @Override
    public void alDesconectado(String mensaje) {
        lblEstadoRespuesta.setText(mensaje);
        habilitarBotones(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTituloPregunta = new javax.swing.JLabel();
        lblNumeroPregunta = new javax.swing.JLabel();
        lblPregunta = new javax.swing.JLabel();
        lblEstadoRespuesta = new javax.swing.JLabel();
        btnOpcion2 = new javax.swing.JButton();
        btnOpcion3 = new javax.swing.JButton();
        btnOpcion1 = new javax.swing.JButton();
        btnOpcion4 = new javax.swing.JButton();
        lblPuntajeTitulo = new javax.swing.JLabel();
        lblPuntajeValor = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(650, 529));

        lblTituloPregunta.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTituloPregunta.setForeground(new java.awt.Color(36, 49, 96));
        lblTituloPregunta.setText("Partida en curso");

        lblNumeroPregunta.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblNumeroPregunta.setForeground(new java.awt.Color(36, 49, 96));
        lblNumeroPregunta.setText("Pregunta:");

        lblPregunta.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblPregunta.setForeground(new java.awt.Color(54, 76, 161));
        lblPregunta.setText("Texto de Pregunta ");

        lblEstadoRespuesta.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblEstadoRespuesta.setForeground(new java.awt.Color(54, 76, 161));
        lblEstadoRespuesta.setText("Seleccione una opcion ");

        btnOpcion2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnOpcion2.setForeground(new java.awt.Color(36, 49, 96));
        btnOpcion2.setText("Opcion 2");
        btnOpcion2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnOpcion2.addActionListener(this::btnOpcion2ActionPerformed);

        btnOpcion3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnOpcion3.setForeground(new java.awt.Color(36, 49, 96));
        btnOpcion3.setText("Opcion 3");
        btnOpcion3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnOpcion3.addActionListener(this::btnOpcion3ActionPerformed);

        btnOpcion1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnOpcion1.setForeground(new java.awt.Color(36, 49, 96));
        btnOpcion1.setText("Opcion 1");
        btnOpcion1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnOpcion1.addActionListener(this::btnOpcion1ActionPerformed);

        btnOpcion4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnOpcion4.setForeground(new java.awt.Color(36, 49, 96));
        btnOpcion4.setText("Opcion 4");
        btnOpcion4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnOpcion4.addActionListener(this::btnOpcion4ActionPerformed);

        lblPuntajeTitulo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblPuntajeTitulo.setForeground(new java.awt.Color(36, 49, 96));
        lblPuntajeTitulo.setText("Puntaje:");

        lblPuntajeValor.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblPuntajeValor.setForeground(new java.awt.Color(36, 49, 96));
        lblPuntajeValor.setText("0");

        jPanel2.setBackground(new java.awt.Color(54, 76, 161));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblPuntajeTitulo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblPuntajeValor, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblEstadoRespuesta)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnOpcion1, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE)
                                .addComponent(btnOpcion2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnOpcion3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnOpcion4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(lblPregunta)
                            .addComponent(lblNumeroPregunta)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(215, 215, 215)
                        .addComponent(lblTituloPregunta)))
                .addContainerGap(190, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(lblTituloPregunta)
                .addGap(30, 30, 30)
                .addComponent(lblNumeroPregunta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPregunta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(lblEstadoRespuesta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnOpcion1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnOpcion2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnOpcion3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnOpcion4, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPuntajeValor)
                    .addComponent(lblPuntajeTitulo))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //Botones
    private void btnOpcion2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpcion2ActionPerformed
        responder(1);
    }//GEN-LAST:event_btnOpcion2ActionPerformed

    private void btnOpcion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpcion1ActionPerformed
        responder(0);
    }//GEN-LAST:event_btnOpcion1ActionPerformed

    private void btnOpcion3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpcion3ActionPerformed
        responder(2);
    }//GEN-LAST:event_btnOpcion3ActionPerformed

    private void btnOpcion4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpcion4ActionPerformed
        responder(3);
    }//GEN-LAST:event_btnOpcion4ActionPerformed


    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOpcion1;
    private javax.swing.JButton btnOpcion2;
    private javax.swing.JButton btnOpcion3;
    private javax.swing.JButton btnOpcion4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblEstadoRespuesta;
    private javax.swing.JLabel lblNumeroPregunta;
    private javax.swing.JLabel lblPregunta;
    private javax.swing.JLabel lblPuntajeTitulo;
    private javax.swing.JLabel lblPuntajeValor;
    private javax.swing.JLabel lblTituloPregunta;
    // End of variables declaration//GEN-END:variables
}
