/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cr.ac.ufide.quiz.cliente.servidor.Vista;
import cr.ac.ufide.quiz.cliente.servidor.Cliente.ClienteJuego;
import cr.ac.ufide.quiz.cliente.servidor.Cliente.EscuchadorCliente;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author jimel
 */
public class FrmResultados extends JFrame implements EscuchadorCliente {

    private ClienteJuego cliente;

    public FrmResultados(ClienteJuego cliente) {
        this.cliente = cliente;

        initComponents(); 
        setLocationRelativeTo(null);
    }

    public void cargarResultados(String nombreGanador, int puntaje, String datosPuntajes) {
        lblGanadorValor.setText(nombreGanador + " con " + puntaje + " puntos");

        DefaultTableModel modelo = (DefaultTableModel) tblPuntajes.getModel();
        modelo.setRowCount(0);

        if (datosPuntajes == null || datosPuntajes.trim().isEmpty()) {
            return;
        }

        String[] jugadores = datosPuntajes.split(";");

        for (int i = 0; i < jugadores.length; i++) {
            String[] partes = jugadores[i].split(":");

            if (partes.length >= 2) {
                modelo.addRow(new Object[]{partes[0], partes[1]});
            }
        }
    }






    @Override
    public void alConectado(String mensaje) {}

    @Override
    public void alError(String mensaje) {}

    @Override
    public void alMensaje(String mensaje) {}

    @Override
    public void alJugadores(String datos) {}

    @Override
    public void alPregunta(String idPregunta, String enunciado, String opciones) {}

    @Override
    public void alResultadoRespuesta(String resultado, int puntos) {}

    @Override
    public void alPuntajes(String datos) {}

    @Override
    public void alGanador(String nombreGanador, int puntaje) {}

    @Override
    public void alDesconectado(String mensaje) {}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblTituloResultados = new javax.swing.JLabel();
        lblGanadorTitulo = new javax.swing.JLabel();
        lblGanadorValor = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPuntajes = new javax.swing.JTable();
        btnCerrar = new javax.swing.JButton();
        btnVolverInicio = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(54, 76, 161));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        lblTituloResultados.setText("Resultados finales");

        lblGanadorTitulo.setText("Ganador");

        lblGanadorValor.setText("Pendiente");

        tblPuntajes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblPuntajes);

        btnCerrar.setText("Cerrar");
        btnCerrar.addActionListener(this::btnCerrarActionPerformed);

        btnVolverInicio.setText("Volver al inicio");
        btnVolverInicio.addActionListener(this::btnVolverInicioActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblGanadorValor)
                            .addComponent(lblGanadorTitulo)
                            .addComponent(lblTituloResultados)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(231, 231, 231)
                        .addComponent(btnCerrar)
                        .addGap(59, 59, 59)
                        .addComponent(btnVolverInicio)))
                .addContainerGap(106, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(133, 133, 133)
                .addComponent(lblTituloResultados)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblGanadorTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblGanadorValor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCerrar)
                    .addComponent(btnVolverInicio))
                .addGap(0, 73, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        if (cliente != null) {
            cliente.salir();
        }
        System.exit(0);
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void btnVolverInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverInicioActionPerformed
        if (cliente != null) {
            cliente.salir();
        }
        dispose();
        new FrmConexion().setVisible(true);
    }//GEN-LAST:event_btnVolverInicioActionPerformed



    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnVolverInicio;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblGanadorTitulo;
    private javax.swing.JLabel lblGanadorValor;
    private javax.swing.JLabel lblTituloResultados;
    private javax.swing.JTable tblPuntajes;
    // End of variables declaration//GEN-END:variables
}
