/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cr.ac.ufide.quiz.cliente.servidor.Vista;
import cr.ac.ufide.quiz.cliente.servidor.Cliente.ClienteJuego;
import cr.ac.ufide.quiz.cliente.servidor.Cliente.EscuchadorCliente;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author jimel
 */
// Esta ventana muestra el ganador final y la tabla de puntajes
public class FrmResultados extends JFrame implements EscuchadorCliente {

    private ClienteJuego cliente;

    public FrmResultados(ClienteJuego cliente) {
        this.cliente = cliente;

        initComponents(); 
        setLocationRelativeTo(null);
    }
    
    // Carga en pantalla el ganador y los puntajes de todos los jugadores
    public void cargarResultados(String nombreGanador, int puntaje, String datosPuntajes) {
        lblGanadorValor.setText(nombreGanador + " con " + puntaje + " puntos");

        DefaultTableModel modelo = (DefaultTableModel) tblPuntajes.getModel();
        modelo.setRowCount(0);

        if (datosPuntajes == null || datosPuntajes.trim().isEmpty()) {
            return;
        }

        String[] jugadores = datosPuntajes.split(";");

        for (int i = 0; i < jugadores.length; i++) {
            String[] partes = jugadores[i].split(":");

            if (partes.length >= 2) {
                modelo.addRow(new Object[]{partes[0], partes[1]});
            }
        }
    }

    @Override
    public void alConectado(String mensaje) {}

    @Override
    public void alError(String mensaje) {}

    @Override
    public void alMensaje(String mensaje) {}

    @Override
    public void alJugadores(String datos) {}

    @Override
    public void alPregunta(String idPregunta, String enunciado, String opciones) {}

    @Override
    public void alResultadoRespuesta(String resultado, int puntos) {}

    @Override
    public void alPuntajes(String datos) {}

    @Override
    public void alGanador(String nombreGanador, int puntaje) {}

    @Override
    public void alDesconectado(String mensaje) {}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblTituloResultados = new javax.swing.JLabel();
        lblGanadorTitulo = new javax.swing.JLabel();
        lblGanadorValor = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPuntajes = new javax.swing.JTable();
        btnCerrar = new javax.swing.JButton();
        btnVolverInicio = new javax.swing.JButton();
        lblSlogan = new javax.swing.JLabel();
        lblSlogan1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(54, 76, 161));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        lblTituloResultados.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTituloResultados.setForeground(new java.awt.Color(36, 49, 96));
        lblTituloResultados.setText("Tabla de puntajes");

        lblGanadorTitulo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblGanadorTitulo.setForeground(new java.awt.Color(91, 150, 244));
        lblGanadorTitulo.setText("Victoria absoluta de");

        lblGanadorValor.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblGanadorValor.setForeground(new java.awt.Color(91, 150, 244));
        lblGanadorValor.setText("Pendiente");

        tblPuntajes.setBackground(new java.awt.Color(204, 204, 204));
        tblPuntajes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Nickname", "Puntaje"
            }
        ));
        tblPuntajes.setGridColor(new java.awt.Color(36, 49, 96));
        tblPuntajes.setSelectionBackground(new java.awt.Color(204, 204, 204));
        jScrollPane1.setViewportView(tblPuntajes);

        btnCerrar.setBackground(new java.awt.Color(97, 168, 224));
        btnCerrar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCerrar.setForeground(new java.awt.Color(255, 255, 255));
        btnCerrar.setText("Cerrar");
        btnCerrar.addActionListener(this::btnCerrarActionPerformed);

        btnVolverInicio.setBackground(new java.awt.Color(97, 168, 224));
        btnVolverInicio.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnVolverInicio.setForeground(new java.awt.Color(255, 255, 255));
        btnVolverInicio.setText("Volver al inicio");
        btnVolverInicio.addActionListener(this::btnVolverInicioActionPerformed);

        lblSlogan.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblSlogan.setForeground(new java.awt.Color(54, 76, 161));
        lblSlogan.setText("Felicidades jugadores");

        lblSlogan1.setForeground(new java.awt.Color(54, 76, 161));
        lblSlogan1.setText("Demás jugadores suerte la próxima");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblSlogan1)
                .addGap(240, 240, 240))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(230, 230, 230)
                        .addComponent(lblTituloResultados))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(245, 245, 245)
                        .addComponent(lblSlogan))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(177, 177, 177)
                        .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(btnVolverInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(lblGanadorTitulo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblGanadorValor)))
                .addContainerGap(151, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(lblTituloResultados)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblSlogan)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGanadorTitulo)
                    .addComponent(lblGanadorValor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSlogan1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVolverInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(35, 35, 35))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //Cierra la sesion actual
    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        if (cliente != null) {
            cliente.salir();
        }
        System.exit(0);
    }//GEN-LAST:event_btnCerrarActionPerformed
    //Vuelve al lobby
    private void btnVolverInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverInicioActionPerformed
        if (cliente != null) {
            cliente.salir();
        }
        dispose();
        new FrmConexion().setVisible(true);
    }//GEN-LAST:event_btnVolverInicioActionPerformed



    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnVolverInicio;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblGanadorTitulo;
    private javax.swing.JLabel lblGanadorValor;
    private javax.swing.JLabel lblSlogan;
    private javax.swing.JLabel lblSlogan1;
    private javax.swing.JLabel lblTituloResultados;
    private javax.swing.JTable tblPuntajes;
    // End of variables declaration//GEN-END:variables
}
