/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cr.ac.ufide.quiz.cliente.servidor.Vista;
import cr.ac.ufide.quiz.cliente.servidor.Cliente.ClienteJuego;
import cr.ac.ufide.quiz.cliente.servidor.Cliente.EscuchadorCliente;
import javax.swing.JFrame;
/**
 *
 * @author jimel
 */


public class FrmSala extends JFrame implements EscuchadorCliente {

    private ClienteJuego cliente;
    private String nickname;

    public FrmSala(ClienteJuego cliente, String nickname) {
        this.cliente = cliente;
        this.nickname = nickname;

        initComponents();
        setLocationRelativeTo(null);

        lblNombreJugador.setText(nickname);
        txtAreaJugadores.setEditable(false);
        lblMensajeSala.setText("Esperando jugadores...");
    }

    @Override
    public void alConectado(String mensaje) {
    }

    @Override
    public void alError(String mensaje) {
        lblMensajeSala.setText(mensaje);
    }

    @Override
    public void alMensaje(String mensaje) {
        lblMensajeSala.setText(mensaje);
    }

    @Override
    public void alJugadores(String datos) {
        txtAreaJugadores.setText("");

        if (datos == null || datos.trim().isEmpty()) {
            return;
        }

        String[] jugadores = datos.split(";");

        for (int i = 0; i < jugadores.length; i++) {
            String[] partes = jugadores[i].split(":");
            if (partes.length >= 3) {
                txtAreaJugadores.append(partes[0] + " - " + partes[1] + " pts - " + partes[2] + "\n");
            }
        }
    }

    @Override
    public void alPregunta(String idPregunta, String enunciado, String opciones) {
        FrmPregunta frmPregunta = new FrmPregunta(cliente, nickname);
        cliente.setEscuchador(frmPregunta);
        frmPregunta.cargarPregunta(idPregunta, enunciado, opciones);
        frmPregunta.setVisible(true);
        dispose();
    }

    @Override
    public void alResultadoRespuesta(String resultado, int puntos) {
    }

    @Override
    public void alPuntajes(String datos) {
    }

    @Override
    public void alGanador(String nombreGanador, int puntaje) {
    }

    @Override
    public void alDesconectado(String mensaje) {
        lblMensajeSala.setText(mensaje);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTituloSala = new javax.swing.JLabel();
        lblJugadorActual = new javax.swing.JLabel();
        lblJugadoresConectados = new javax.swing.JLabel();
        lblEstadoSala = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblNombreJugador = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaJugadores = new javax.swing.JTextArea();
        btnListo = new javax.swing.JButton();
        btnIniciarManual = new javax.swing.JButton();
        btnSalirSala = new javax.swing.JButton();
        lblMensajeSala = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lblTituloSala.setText(" Sala de espera");

        lblJugadorActual.setText("Jugador actual");

        lblJugadoresConectados.setText("Jugadores conectados");

        lblEstadoSala.setText("Estado de la sala");

        jPanel2.setBackground(new java.awt.Color(54, 76, 161));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        lblNombreJugador.setText("Sin conectar");

        txtAreaJugadores.setColumns(20);
        txtAreaJugadores.setRows(5);
        jScrollPane1.setViewportView(txtAreaJugadores);

        btnListo.setText("Estoy listo");
        btnListo.addActionListener(this::btnListoActionPerformed);

        btnIniciarManual.setText("Iniciar");
        btnIniciarManual.addActionListener(this::btnIniciarManualActionPerformed);

        btnSalirSala.setText("Salir");
        btnSalirSala.addActionListener(this::btnSalirSalaActionPerformed);

        lblMensajeSala.setText("Esperando jugadores");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNombreJugador)
                            .addComponent(lblEstadoSala)
                            .addComponent(lblJugadorActual)
                            .addComponent(lblJugadoresConectados)
                            .addComponent(lblTituloSala)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 563, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(btnListo)
                        .addGap(51, 51, 51)
                        .addComponent(btnIniciarManual)
                        .addGap(53, 53, 53)
                        .addComponent(btnSalirSala))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(252, 252, 252)
                        .addComponent(lblMensajeSala)))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addComponent(lblTituloSala)
                .addGap(18, 18, 18)
                .addComponent(lblJugadorActual)
                .addGap(18, 18, 18)
                .addComponent(lblJugadoresConectados)
                .addGap(18, 18, 18)
                .addComponent(lblEstadoSala)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblNombreJugador)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnListo)
                    .addComponent(btnIniciarManual)
                    .addComponent(btnSalirSala))
                .addGap(18, 18, 18)
                .addComponent(lblMensajeSala)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnListoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListoActionPerformed
        cliente.enviarListo();
        btnListo.setEnabled(false);
        lblMensajeSala.setText("Marcado como listo");
    }//GEN-LAST:event_btnListoActionPerformed

    private void btnIniciarManualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarManualActionPerformed
    lblMensajeSala.setText("Esperando a que todos esten listos");
    }//GEN-LAST:event_btnIniciarManualActionPerformed

    private void btnSalirSalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirSalaActionPerformed
        cliente.salir();
        dispose();
        new FrmConexion().setVisible(true);
    }//GEN-LAST:event_btnSalirSalaActionPerformed





  
    /**s
     * @param args the command line arguments
     */
    
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIniciarManual;
    private javax.swing.JButton btnListo;
    private javax.swing.JButton btnSalirSala;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblEstadoSala;
    private javax.swing.JLabel lblJugadorActual;
    private javax.swing.JLabel lblJugadoresConectados;
    private javax.swing.JLabel lblMensajeSala;
    private javax.swing.JLabel lblNombreJugador;
    private javax.swing.JLabel lblTituloSala;
    private javax.swing.JTextArea txtAreaJugadores;
    // End of variables declaration//GEN-END:variables
}
