/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cr.ac.ufide.quiz.cliente.servidor.Vista;
import cr.ac.ufide.quiz.cliente.servidor.Cliente.ClienteJuego;
import cr.ac.ufide.quiz.cliente.servidor.Cliente.EscuchadorCliente;
import javax.swing.JFrame;
/**
 *
 * @author jimel
 */


public class FrmSala extends JFrame implements EscuchadorCliente {

    private ClienteJuego cliente;
    private String nickname;

    public FrmSala(ClienteJuego cliente, String nickname) {
        this.cliente = cliente;
        this.nickname = nickname;

        initComponents();
        setLocationRelativeTo(null);

        lblNombreJugador.setText(nickname);
        txtAreaJugadores.setEditable(false);
        lblMensajeSala.setText("Esperando jugadores...");
    }

    @Override
    public void alConectado(String mensaje) {
    }

    @Override
    public void alError(String mensaje) {
        lblMensajeSala.setText(mensaje);
    }

    @Override
    public void alMensaje(String mensaje) {
        lblMensajeSala.setText(mensaje);
    }

    @Override
    public void alJugadores(String datos) {
        txtAreaJugadores.setText("");

        if (datos == null || datos.trim().isEmpty()) {
            return;
        }

        String[] jugadores = datos.split(";");

        for (int i = 0; i < jugadores.length; i++) {
            String[] partes = jugadores[i].split(":");
            if (partes.length >= 3) {
                txtAreaJugadores.append(partes[0] + " - " + partes[1] + " pts - " + partes[2] + "\n");
            }
        }
    }

    @Override
    public void alPregunta(String idPregunta, String enunciado, String opciones) {
        FrmPregunta frmPregunta = new FrmPregunta(cliente, nickname);
        cliente.setEscuchador(frmPregunta);
        frmPregunta.cargarPregunta(idPregunta, enunciado, opciones);
        frmPregunta.setVisible(true);
        dispose();
    }

    @Override
    public void alResultadoRespuesta(String resultado, int puntos) {
    }

    @Override
    public void alPuntajes(String datos) {
    }

    @Override
    public void alGanador(String nombreGanador, int puntaje) {
    }

    @Override
    public void alDesconectado(String mensaje) {
        lblMensajeSala.setText(mensaje);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTituloSala = new javax.swing.JLabel();
        lblJugadorActual = new javax.swing.JLabel();
        lblJugadoresConectados = new javax.swing.JLabel();
        lblEstadoSala = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblNombreJugador = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaJugadores = new javax.swing.JTextArea();
        btnListo = new javax.swing.JButton();
        btnIniciarManual = new javax.swing.JButton();
        btnSalirSala = new javax.swing.JButton();
        lblMensajeSala = new javax.swing.JLabel();
        lblSlogan = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(650, 629));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(650, 629));

        lblTituloSala.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTituloSala.setForeground(new java.awt.Color(36, 49, 96));
        lblTituloSala.setText(" Sala de juego");

        lblJugadorActual.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblJugadorActual.setForeground(new java.awt.Color(36, 49, 96));
        lblJugadorActual.setText("Jugador actual:");

        lblJugadoresConectados.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblJugadoresConectados.setForeground(new java.awt.Color(36, 49, 96));
        lblJugadoresConectados.setText("Jugadores conectados");

        lblEstadoSala.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblEstadoSala.setForeground(new java.awt.Color(36, 49, 96));
        lblEstadoSala.setText("Estado de la sala");

        jPanel2.setBackground(new java.awt.Color(54, 76, 161));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        lblNombreJugador.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNombreJugador.setForeground(new java.awt.Color(36, 49, 96));
        lblNombreJugador.setText("Sin conectar");

        txtAreaJugadores.setColumns(20);
        txtAreaJugadores.setRows(5);
        txtAreaJugadores.setCaretColor(new java.awt.Color(36, 49, 96));
        jScrollPane1.setViewportView(txtAreaJugadores);

        btnListo.setBackground(new java.awt.Color(97, 168, 224));
        btnListo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnListo.setForeground(new java.awt.Color(255, 255, 255));
        btnListo.setText("Estoy listo");
        btnListo.setPreferredSize(new java.awt.Dimension(90, 27));
        btnListo.addActionListener(this::btnListoActionPerformed);

        btnIniciarManual.setBackground(new java.awt.Color(97, 168, 224));
        btnIniciarManual.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnIniciarManual.setForeground(new java.awt.Color(255, 255, 255));
        btnIniciarManual.setText("Iniciar");
        btnIniciarManual.addActionListener(this::btnIniciarManualActionPerformed);

        btnSalirSala.setBackground(new java.awt.Color(97, 168, 224));
        btnSalirSala.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSalirSala.setForeground(new java.awt.Color(255, 255, 255));
        btnSalirSala.setText("Salir");
        btnSalirSala.addActionListener(this::btnSalirSalaActionPerformed);

        lblMensajeSala.setForeground(new java.awt.Color(120, 121, 121));
        lblMensajeSala.setText("Esperando jugadores...");

        lblSlogan.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblSlogan.setForeground(new java.awt.Color(54, 76, 161));
        lblSlogan.setText("La partida inicia pronto");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(116, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblJugadoresConectados)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblJugadorActual)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblNombreJugador))
                    .addComponent(lblEstadoSala))
                .addGap(112, 112, 112))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnListo, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnIniciarManual, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(73, 73, 73)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblMensajeSala)
                                    .addComponent(btnSalirSala, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(234, 234, 234)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSlogan, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(lblTituloSala)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(lblTituloSala)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSlogan)
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblJugadorActual)
                    .addComponent(lblNombreJugador))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblJugadoresConectados)
                .addGap(7, 7, 7)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblEstadoSala)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnIniciarManual, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnListo, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSalirSala, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblMensajeSala)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnListoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListoActionPerformed
        cliente.enviarListo();
        btnListo.setEnabled(false);
        lblMensajeSala.setText("Marcado como listo");
    }//GEN-LAST:event_btnListoActionPerformed

    private void btnIniciarManualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarManualActionPerformed
    lblMensajeSala.setText("Esperando a que todos esten listos");
    }//GEN-LAST:event_btnIniciarManualActionPerformed

    private void btnSalirSalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirSalaActionPerformed
        cliente.salir();
        dispose();
        new FrmConexion().setVisible(true);
    }//GEN-LAST:event_btnSalirSalaActionPerformed





  
    /**s
     * @param args the command line arguments
     */
    
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIniciarManual;
    private javax.swing.JButton btnListo;
    private javax.swing.JButton btnSalirSala;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblEstadoSala;
    private javax.swing.JLabel lblJugadorActual;
    private javax.swing.JLabel lblJugadoresConectados;
    private javax.swing.JLabel lblMensajeSala;
    private javax.swing.JLabel lblNombreJugador;
    private javax.swing.JLabel lblSlogan;
    private javax.swing.JLabel lblTituloSala;
    private javax.swing.JTextArea txtAreaJugadores;
    // End of variables declaration//GEN-END:variables
}
